name: Run Returns Automation

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    # 👇 this removes the Node20 warning
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Create service account file
        run: echo '${{ secrets.GOOGLE_SERVICE_ACCOUNT }}' > service-account.json

      - name: Run automation
        run: node main.js
